[project]
name = "backend-draft"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<4.0.0"
dependencies = [
    "langchain-community>=0.3.20",
    "streamlit>=1.43.2",
]

[tool.uv.sources]
agent-ui = { path = "./agent-ui" }
wids-agent-api = { path = "./wids-agent-api" }
wids-ai-agents = { path = "./wids-ai-agents" }

[tool.uv.workspace]
members = ["wids-agent-api", "agent-ui", "wids-ai-agents"]
